name: dodi
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.1.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  charts_flutter: ^0.10.0
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/classes/
    - assets/image/introduction/
    - assets/image/socialmedia/
    - assets/image/analyzing.png
    - assets/image/line.png
    - assets/image/result.png
    - assets/image/profile.png
    - assets/image/mockquestions/soru1.png
    - assets/image/mockquestions/soru2.png
    - assets/image/mockquestions/soru3.png
    - assets/image/mockquestions/cevap1.png
    - assets/image/mockquestions/cevap2.png
    - assets/image/mockquestions/cevap3.png

flutter_native_splash:
  background_image : assets/splash.png
  andorid: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill